#[derive(Debug)]
pub enum Token {
    Identifier(TokenData),
    String(TokenData),
    Comment(TokenData),
    UnknownCharacter(char),
    LiteralNumber(TokenData),

    KeywordLocal,
    KeywordIf,
    KeywordThen,
    KeywordEnd,
    KeywordElse,
    KeywordElseif,
    KeywordWhile,
    KeywordRepeat,
    KeywordUntil,
    KeywordDo,
    KeywordIn,
    KeywordBreak,
    KeywordContinue,
    KeywordReturn,
    KeywordAnd,
    KeywordOr,
    KeywordNot,
    KeywordFor,
    KeywordFunction,

    OpenedBracket,
    ClosedBracket,
    OpenedSquareBracket,
    ClosedSquareBracket,
    OpenedCurlyBracket,
    ClosedCurlyBracket,

    LiteralNil,
    LiteralTrue,
    LiteralFalse,

    OperatorEquality,
    OperatorAssignment,
    OperatorGreaterOrEqual,
    OperatorGreater,
    OperatorLowerOrEqual,
    OperatorLower,
    OperatorAdditionAssignment,
    OperatorAddition,
    OperatorSubtractionAssignment,
    OperatorSubtraction,
    OperatorModulusAssignment,
    OperatorModulus,
    OperatorPowerAssignment,
    OperatorPower,
    OperatorDivisionAssignment,
    OperatorDivision,
    OperatorMultiplicationAssignment,
    OperatorMultiplication,
    OperatorLen,
    OperatorUnary,
}
#[derive(Debug)]
pub struct TokenData {
    pub source: String,
}